Manually parse requirements.txt rather than use pip.req.parse_requirements
It was resulting in the following error on heroku:
TypeError: parse_requirements() missing 1 required keyword argument: 'session'